@startuml
component log
component threadpoll
component server
component timer
component CGImysql
component http
CGImysql ..>log
http ..>log
http ..>CGImysql
threadpoll ..>httpgit config --global user.name
git config --global user.email
threadpoll ..>log 
server ..>http
server ..>threadpoll
server ..>timer
server ..>log
server ..>CGImysql
@enduml
